apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: johnmops/jen-ansible:1.0
          ports:
            - containerPort: 3000

---

#Connects the internal pods without access from the outside world.
apiVersion: v1
kind: Service
metadata:
  name: client-cluster
spec:
  type: ClusterIP
  selector:
    component: web
  ports:
    - port: 3000 #can be different
      targetPort: 3000