apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-dp
spec:
  replicas: 2
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
     containers:
       - name: client
         image: johnmops/jen-ansible:1.0
         ports:
           - containerPort: 3000
