apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      image: johnmops/jen-ansible:lts
      ports:
        - containerPort: 8080