---

- name: Increase memory
  raw: sysctl -w vm.max_map_count=262144

- name: Ensure group "logstash" group exists
  group:
    name: logstash
    state: present

- name: Add the user 'lg' with a specific uid and a primary group of 'kibana'
  user:
    name: lg
    uid: 1003
    group: logstash

- name: Create Logstash folder
  file:
    path: /opt/logstash-{{ es_version }}
    state: directory
    owner: 1003
    group: logstash
  with_items:
    - "{{ lg_path }}-{{ es_version }}"
    - "{{ lg_path }}-{{ es_version }}/pipelines"

- name: Move log4j2.properties templates
  template:
    src: "{{ item }}"
    dest: /opt/logstash-{{ es_version }}/{{ item }}
    owner: 1003
    group: logstash
  with_items:
    - log4j2.properties
    - jvm.options
    - logstash.yml
    - pipelines.yml

- name: Move logstash.conf templates
  template:
    src: logstash.conf
    dest: "{{ lg_path }}-{{ es_version }}/pipelines"
    owner: 1003
    group: logstash

- name: Run Logstash Docker
  docker_container:
    name: logstash
    hostname: logstash
    image: docker.elastic.co/logstash/logstash:{{ es_version }}
    state: started
    links:
      - "elasticsearch"
    volumes:
      - /{{ lg_path }}-{{ es_version }}:/usr/share/logstash/config
      - /{{ lg_path }}-{{ es_version }}/pipelines:/usr/share/logstash/pipeline
    ports:
     - "5044:5044"
     - "9600:9600"
     - "9700:9700"
