---

#- name: Log into DockerHub
#  docker_login:
#    username: yourusername #use only in private repository
#    password: yourpassword #use only in private repository

  

- name: Git clone
  git:
      repo: 'https://github.com/JohnMops/Mops-DevOps-Life'
      dest: /opt/Mops

- name: Build an image
  docker_image:
    build:
      path: /opt/Mops/appU
    name: johnmops/project
    tag: '{{ buildV }}'
    #push: yes
    source: build
    
- name: Start the built image
  docker_container:
    name: flask
    image: johnmops/project:{{ buildV }}
    state: started
    restart: yes
    ports:
     - "80:80"
     
#- name: Check that you can connect (GET) to a page and it returns a status 200
 # uri:
  #  url: http://52.58.213.55

- name: Check that a page returns a status 200 and fail if 'Hello World' is not in the page contents
  uri:
    url: http://52.58.213.55
    return_content: yes
  register: out
  failed_when: "'Hello World' not in out.content"
