---
- name: Git clone
  git:
      repo: 'https://github.com/JohnMops/Mops-DevOps-Life/tree/master/appU'
      dest: /opt/Mops

- name: Build an image and push it to a private repo
  docker_image:
    build:
      path: ./opt/Mops/Mops-DevOps-Life/appU
    name: johnmops/project
    tag: '{{ buildv }}'
    push: yes
    source: build
